version: "3.8"

services:
  api:
    build: .
    container_name: math-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    working_dir: /app
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: math-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
